// CONTADOR
export const INCREMENTAR = 'INCREMENTAR'
export const DECREMENTAR = 'DECREMENTAR'

// MAQ EXPENDEDORA
export const SACAR_PRODUCTO = 'SACAR_PRODUCTO'
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS'
export const INICIALIZAR_PRODUCTOS = 'INICIALIZAR_PRODUCTOS'